# Mathematics

In [2]:
import numpy as np

In [14]:
a = np.array([1,2,3,4])
print("Matrix 'a':")
print(a)
print()

print("Adding 2 to matrix 'a':")
print(a+2)
print()

print("Subtracting 2 to matrix 'a':")
print(a-2)
print()

print("Multiplying 2 to matrix 'a':")
print(a*2)
print()

print("Dividing 2 to matrix 'a':")
print(a/2)
print()

print("Squared matrix 'a':")
print(a**2)


Matrix 'a':
[1 2 3 4]

Adding 2 to matrix 'a':
[3 4 5 6]

Subtracting 2 to matrix 'a':
[-1  0  1  2]

Multiplying 2 to matrix 'a':
[2 4 6 8]

Dividing 2 to matrix 'a':
[0.5 1.  1.5 2. ]

Squared matrix 'a':
[ 1  4  9 16]


## Adding multiple matrices

In [17]:
a = np.array([1,2,3,4])
print("Matrix 'a':")
print(a)
print()

b = np.array([4,3,2,1])
print("Matrix 'b':")
print(b)
print()

c = a + b
print("Matrix 'c = a + b':")
print(c)
print()

Matrix 'a':
[1 2 3 4]

Matrix 'b':
[4 3 2 1]

Matrix 'c = a + b':
[5 5 5 5]



## Sin, Cos, etc

In [26]:
a = np.array([45,90,135,180])
print("Matrix 'a':")
print(a)
print()

print("Sin of Matrix 'a':")
sin = np.sin(a)
print(sin)
print()

print("Cosine of Matrix 'a':")
sin = np.cos(a)
print(sin)
print()


Matrix 'a':
[ 45  90 135 180]

Sin of Matrix 'a':
[ 0.85090352  0.89399666  0.08836869 -0.80115264]

Cosine of Matrix 'a':
[ 0.52532199 -0.44807362 -0.99608784 -0.59846007]



# Linear Algebra

In [29]:
a = np.ones((2,3))
print("Matrix a :")
print(a)

b = np.full((3,2),2)
print("Matrix b :")
print(b)

# a*b will not work, because the soze of the matrices is not the same.
# Use 'matmul" function of numpy

c = np.matmul(a,b)
print("Matrix multiplication of a and b:")
print(c)


Matrix a :
[[1. 1. 1.]
 [1. 1. 1.]]
Matrix b :
[[2 2]
 [2 2]
 [2 2]]
Matrix multiplication of a and b:
[[6. 6.]
 [6. 6.]]


## Find the determinant of an identity matrix

In [36]:
c = np.identity(3)
print("Matrix c :")
print(c)
print()

determinant=np.linalg.det(c)
print(" Determinant of the Matrix 'c':")
print(determinant)
print()

d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix d :")
print(d)
print()
det_d = np.linalg.det(d)
print(" Determinant of the Matrix 'd':")
print(det_d)

Matrix c :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 Determinant of the Matrix 'c':
1.0

Matrix d :
[[1 2 3]
 [4 5 6]
 [7 8 9]]

 Determinant of the Matrix 'd':
0.0


## Normalization of a Matrix

In [42]:
print("Matrix d :")
print(d)
print()

norm_d = np.linalg.norm(d, axis=1)
print(" Normalization of the Matrix 'd':")
print(norm_d)

Matrix d :
[[1 2 3]
 [4 5 6]
 [7 8 9]]

 Normalization of the Matrix 'd':
[ 3.74165739  8.77496439 13.92838828]


## Statistics

In [50]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("array :")
print(arr)

print("Min of array:", np.min(arr))
print("Max of array:", np.max(arr))
print("Sum of array(axis = 0) i.e. sum of all matrix:", np.sum(arr, axis=0))
print("Sum of array(axis = 1) i.e. sum inside each matrix:", np.sum(arr, axis=1))

array :
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Min of array: 1
Max of array: 9
Sum of array(axis = 0) i.e. sum of all matrix: [12 15 18]
Sum of array(axis = 1) i.e. sum inside each matrix: [ 6 15 24]


## Reorganizing arrays

In [62]:
array1 = np.array([[1,2,3,4],[5,6,7,8]])
print("array 1 :")
print(array1)
print()
print("Shape of array 1 :")
print(array1.shape)
print()

array_4_by_2 = array1.reshape((4,2))
print("array 1 reshaped to 4 by 2 matrix:")
print(array_4_by_2)
print()

array_2x2x2 = array1.reshape((2,2,2))
print("array 1 reshaped to 2x2x2 matrix:")
print(array_2x2x2)
print()

array_8_by_1 = array1.reshape((8,1))
print("array 1 reshaped to 8 by 1 matrix:")
print(array_8_by_1)



array 1 :
[[1 2 3 4]
 [5 6 7 8]]

Shape of array 1 :
(2, 4)

array 1 reshaped to 4 by 2 matrix:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

array 1 reshaped to 2x2x2 matrix:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

array 1 reshaped to 8 by 1 matrix:
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


## Vertically stacking Vectors or matrices

In [69]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print("Vector 1:")
print(v1)
print()
print("Vector 2:")
print(v2)
print()

# Single vertical stacking
print("v1 stacked over v2:")
v3 = np.vstack((v1,v2))
print(v3)
print()


# Multiple Vertical stacking

v4 = np.vstack([v1,v1,v2,v2])
print("v1 stacked over v1, stacked over v2, stacked over v2:")
print(v4)

Vector 1:
[1 2 3 4]

Vector 2:
[5 6 7 8]

v1 stacked over v2:
[[1 2 3 4]
 [5 6 7 8]]

v1 stacked over v1, stacked over v2, stacked over v2:
[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


## Horizontal stacking of Vectors

In [76]:
h1 = np.ones((2,4))
print(h1)
print()

h2 = np.zeros((2,2))
print(h2)
print()

h3 = np.hstack((h1,h2))
print(h3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0. 0.]
 [0. 0.]]

[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]
