# Numpy Tutorial : Basics

## Declare an Array or matrix

In [5]:
import numpy as np

In [6]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [20]:
b = np.array([[1.0,2.0,5.0],[6.0,5.0,4.0],[3.0,7.0,1.0]], dtype='int16')
print(b)

[[1 2 5]
 [6 5 4]
 [3 7 1]]


## Get Dimensions

In [21]:
#get Dimensions


print("Dimension of a : ", a.ndim)
print("Dimension of b : ", b.ndim)

Dimension of a :  1
Dimension of b :  2


## Get Shape - number of Columns and Rows of the matrix.

In [22]:
# get Shapes of the matrix
print("Matrix a = ", a)
print("Shape of matrix a : ", a.shape)
print("As there are", a.shape[0], "columns in matrix 'a'")
print("Matrix b = ", b)
print("Shape of matrix b : ", b.shape)
print("As there are", b.shape[0], "columns and", b.shape[1], "rows in Matrix 'b'")

Matrix a =  [1 2 3]
Shape of matrix a :  (3,)
As there are 3 columns in matrix 'a'
Matrix b =  [[1 2 5]
 [6 5 4]
 [3 7 1]]
Shape of matrix b :  (3, 3)
As there are 3 columns and 3 rows in Matrix 'b'


In [23]:
c = np.array([[1.0,2.0,5.0],[6.0,5.0,4.0]])
print("Matrix c = ", c)
print("Shape of matrix c : ", c.shape)
print("As there are", c.shape[0], "columns and", c.shape[1], "rows in Matrix 'b'")

Matrix c =  [[1. 2. 5.]
 [6. 5. 4.]]
Shape of matrix c :  (2, 3)
As there are 2 columns and 3 rows in Matrix 'b'


## Get Datatype and assign data type

In [30]:
#get the data Type

print("Data type of 'a': ", a.dtype)
print("Data type of 'b': ", b.dtype)
print("Data type of 'c': ", c.dtype)

Data type of 'a':  int32
Data type of 'b':  int16
Data type of 'c':  float64


In [31]:
#assign Data Type at the time of declating the matrix

d = np.array([[1.0,2.0,5.0],[6.0,5.0,4.0]], dtype='int32')
print("Matrix d = ", d)
print("Data type of matrix d : ", d.dtype)

Matrix d =  [[1 2 5]
 [6 5 4]]
Data type of matrix d :  int32


## Get the item Size of each item in the Matrix

In [29]:
# Get the item Size of each item in the Matrix

# assign Data Type at the time of declating the matrix

e = np.array([[1.0,2.0,5.0],[6.0,5.0,4.0]], dtype='int16')
print("Matrix e = ", e)
print("Data type of matrix e : ", e.dtype)
print("Item Size of matrix e : ", e.itemsize, "bytes.")

print("Matrix d = ", )
print("Data type of matrix d : ", d.dtype)
print("Item Size of matrix d : ", d.itemsize, "bytes")

print("Notice the Integer type as int16 for matrix 'e', whereas, even though matrix 'e' and 'd' has the same content the item size for the two matrix are different")


Matrix e =  [[1 2 5]
 [6 5 4]]
Data type of matrix e :  int16
Item Size of matrix e :  2 bytes.
Matrix d = 
Data type of matrix d :  int32
Item Size of matrix d :  4 bytes
Notice the Integer type as int16 for matrix 'e', whereas, even though matrix 'e' and 'd' has the same content the item size for the two matrix are different


## Get the total Size of the Matrix also __nbytes__ function.

In [34]:
# get Total size

f = np.array([[1,2,3],[4,5,6]])

print("Matrix f = ", e)

f_size = f.size
print("'Size' or total number of elements of matrix 'f' : ", f_size)

f_item_size = f.itemsize
print("Item Size of matrix d : ", f_item_size, "bytes")

print("total size by the formula, i.e.," "\n" "(total number of elements also called 'size') * (size of each item in bytes, called ItemSize)")

total_size_f = f_size*f_item_size

print("total size = ", total_size_f, "bytes")

print("'nbytes' function also provides the same value as shown below:")
f_nbytes = f.nbytes
print(f_nbytes, "bytes")




      

Matrix f =  [[1 2 5]
 [6 5 4]]
'Size' or total number of elements of matrix 'f' :  6
Item Size of matrix d :  4 bytes
total size by the formula, i.e.,
(total number of elements also called 'size') * (size of each item in bytes, called ItemSize)
total size =  24 bytes
'nbytes' function also provides the same value as shown below:
24 bytes


In [33]:
# Lets get the total size of Matrix 'a' and 'b" declared earlier with int and float datatypes

print("Using formula")
print("matrix a = ",a)
a_size = a.size
print("Data type of matrix a : ", a.dtype)
a_itemsize = a.itemsize
a_totalsize = a_size * a_itemsize
print ("Total size of 'a' :", a_totalsize, "bytes")
print()

print("Using function nbytes")
print("matrix b = ",b)
b_size = b.size
print("Data type of matrix b : ", b.dtype)
b_itemsize = b.itemsize
b_totalsize = b.nbytes
print ("Total size of 'b' :", b_totalsize, "bytes")


Using formula
matrix a =  [1 2 3]
Data type of matrix a :  int32
Total size of 'a' : 12 bytes

Using function nbytes
matrix b =  [[1 2 5]
 [6 5 4]
 [3 7 1]]
Data type of matrix b :  int16
Total size of 'b' : 18 bytes
