# Accessing/changing specific elements, rows and columns

In [2]:
## Import NumPy
import numpy as np

## Declaring a new Matrix

In [5]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print("a = ")
print(a)

a = 
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


## Accessing a specific element

In [16]:
# Printing first element 

print("Shape of the matrix : ", a.shape)

el_01 = a[0,0]
print("1st Element : ", el_01)

# Printing Second element 

el_02 = a[0,1]
print("2nd Element : ", el_02)

# Printing eighth element 

el_08 = a[1,0]
print("8th Element : ", el_08)

# Printing the 10th element i.e.,row 2 column 3
# Remember index starts 

el_10 = a[1,2]
print("10th Element : ", el_10)



Shape of the matrix :  (2, 7)
1st Element :  1
2nd Element :  2
8th Element :  8
10th Element :  10


## Accessing a Specific Row

In [18]:
a_row_1 = a[0,:]
print("Row 1 = ", a_row_1)

a_row_2 = a[1,:]
print("Row 2 = ", a_row_2)

Row 1 =  [1 2 3 4 5 6 7]
Row 2 =  [ 8  9 10 11 12 13 14]


## Accessing a Specific Row

In [20]:
a_col_1 = a[:,0]
print("Column 1 = ", a_col_1)

a_col_2 = a[:,1]
print("Column 2 = ", a_col_2)

a_col_7 = a[:,6]
print("Column 6 = ", a_col_7)

Column 1 =  [1 8]
Column 2 =  [2 9]
Column 6 =  [ 7 14]


## Skipping rows and columns

In [21]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [29]:
# Print 2, 4 and 6
a_skip = a[0,1:6:2]
print(a_skip)
a_skip_neg = a[0,2:-1:2]
print(a_skip_neg)

[2 4 6]
[3 5]


In [35]:
a_col_skip = a[:,1:6:2]
print(a_col_skip)

[[ 2  4  6]
 [ 9 11 13]]


## Assigning value to an element

In [13]:
b = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print("b = ")
print(b)
b_4th_elem = b[0,3]
print("forth element = ", b_4th_elem)

# Changing or assignin new value to an element

b[0,3] = 20
print("Changed 4th Element = ", b[0,3])


b = 
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
forth element =  4
Changed 4th Element =  20


## Changing an entire column

In [19]:
b = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print("b = ")
print(b)
column_2 = b[:,2]
print("Column 2 = ", column_2)

#Assign another value to the entire columns

b[:,2] = 5
print("Changed Column 2 = ", b[:,2])

b[:,2] = [1,2]
print("Again changed Column 2 = ", b[:,2])



b = 
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
Column 2 =  [ 3 10]
Changed Column 2 =  [5 5]
Again changed Column 2 =  [1 2]


## Defining a 3-d Array

In [27]:
# Pay attention to the arrangement of the Square Brackets.
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

# Now lets print 4 from this 3-d matrix
# Start from the outside of the matrix
# 0 for the first 2-d matrix inside the 3-d matrix
# 1 for the second row index inside the chosen 2-D matrix
# 1 for the second element index in side the choses row.
element = c[0,1,1]
print(element)

c[0,1,1] = 92
print()

new_element = c[0,1,1]
print(new_element)
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4

92
[[[ 1  2]
  [ 3 92]]

 [[ 5  6]
  [ 7  8]]]


In [29]:
# Updating entire context of a 2-d matrix inside a 3-D matrix
c[0,:,:] = [[11,12],[13,14]]
print(c)

[[[11 12]
  [13 14]]

 [[ 5  6]
  [ 7  8]]]


In [30]:
# Updating entire column of a 2-d matrix inside a 3-D matrix
c[1,:,1] = [33,33]
print(c)

[[[11 12]
  [13 14]]

 [[ 5 33]
  [ 7 33]]]


In [31]:
# Updating entire row of a 2-d matrix inside a 3-D matrix
c[1,0,:] = [20,20]
print(c)

[[[11 12]
  [13 14]]

 [[20 20]
  [ 7 33]]]


In [32]:
# Updating entire row of all the 2-d matrices inside a 3-D matrix
c[:,0,:] = [10,10]
print(c)

[[[10 10]
  [13 14]]

 [[10 10]
  [ 7 33]]]
