# Initializing different types of Arrays

In [2]:
import numpy as np

## Initialize all zero matrix

In [3]:
c = np.zeros(4)
print(c)

[0. 0. 0. 0.]


In [5]:
c = np.zeros((3,2))
print(c)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [9]:
c = np.zeros((3,2,3))
print(c)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


## Initialize all ones matrix

In [11]:
d = np.ones((1,2), dtype = 'int16')
print(d)

[[1 1]]


## Initialize any other value to each element of a matrix

In [13]:
e = np.full((2,2), 33, dtype = 'int16')
print(e)

[[33 33]
 [33 33]]


## Initialize like another matrix using __full_like__

In [15]:
f = np.full_like(c,22)
print(f)

[[[22. 22. 22.]
  [22. 22. 22.]]

 [[22. 22. 22.]
  [22. 22. 22.]]

 [[22. 22. 22.]
  [22. 22. 22.]]]


## Intialize a matrix with Random Numbers

In [23]:
# The below random function gives the output with elements as floats.
g = np.random.rand(4,2)
print(g)

[[0.09112248 0.02663789]
 [0.51186089 0.68977019]
 [0.09882131 0.2606059 ]
 [0.64328337 0.13323574]]


In [24]:
#Creating random matrix with sample shape of another matrix 'g'.

f = np.random.random_sample(g.shape)
print(f)

[[0.88293013 0.55598434]
 [0.70554477 0.30776301]
 [0.15064128 0.87273265]
 [0.30853244 0.55959446]]


In [33]:
# RANDOM.RANDINT() function here is taking 2 values as parameters
# '-5' as the start limit of the random value
# '20' as th outer limit of the random value
# 'size" as the shape of the matrix desired.

random_int_matrix = np.random.randint(-5,20, size=(3,3))
print(random_int_matrix)

[[15 18 17]
 [ 5 11  4]
 [19 -5  2]]


## Identity Matrix

In [34]:
identity_matrix = np.identity(5)
print(identity_matrix) 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Repeat the array

In [42]:
orig_array = np.array([[1,2,3]])
repeated_array = np.repeat(orig_array, 3, axis=0)
print("with Axis as 0: ")
print(repeated_array)
print()

repeated_array = np.repeat(orig_array, 3, axis=1)
print("with Axis as 1: ")
print(repeated_array)

with Axis as 0: 
[[1 2 3]
 [1 2 3]
 [1 2 3]]

with Axis as 1: 
[[1 1 1 2 2 2 3 3 3]]


# Test Task
## Try to make the following matrix

- 1 1 1 1 1 
- 1 0 0 0 1
- 1 0 9 0 1
- 1 0 0 0 1
- 1 1 1 1 1

### Using all the functions used above.


## Solution 01

In [49]:
a=np.full((5,5), 1)
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [63]:
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [64]:
a[2,2] = 9
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Solution 02

In [66]:
a = np.ones((5,5))
print(a)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

a[1:-1,1:-1] = z
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Copying an array
### Using __copy__ function

In [73]:
## Wrong way to copy matrix

a=np.array([1,2,3])
print(a)

b = a
print()
print(b)

b[1] = 100
print()
print(b)

print()
print("A is also changed to :")
print(a)
print()

print("Therefore, do not use 'equals to' to make copies of matrix. Instead use copy function as shown below")



[1 2 3]

[1 2 3]

[  1 100   3]

A is also changed to :
[  1 100   3]

Therefore, do not use 'equals to' to make copies of matrix. Instead use copy function as shown below


In [75]:
a=np.array([1,2,3])
print(a)

# Copy function, copies the contents of one matrix to another.
b = a.copy()
print()
print(b)

b[1] = 100
print()
print(b)

print()
print("A is not changed to :")
print(a)
print()

[1 2 3]

[1 2 3]

[  1 100   3]

A is not changed to :
[1 2 3]

