# Miscellaeous

## Loading from a file

In [13]:
import numpy as np

filedata = np.genfromtxt('numbers.txt', delimiter = ',')
filedata = filedata.astype('int32')
print(filedata)
print()

filedata_min = np.min(filedata)
print("Min of filedata :", filedata_min)
print()

filedata_max = np.max(filedata)
print("Max of filedata :", filedata_max)
print()

filedata_sum = np.sum(filedata)
print("Sum of filedata :", filedata_sum)


[[43 22  7 85 14 99 55 36 61 10]
 [83 79 58 57 80 18 97 54 35 29]
 [53 63 13 27 92 88 62  9 26 60]
 [91 32 17 46 31 71 16 74 11 39]
 [59 67 41 86 19 20 94 47 25 37]
 [ 1 81 82 65 28 40 45 68 30 33]
 [70 42 44 95 76 50 77 73 90 48]
 [72 21  5 38 75 69 56 84 23 87]
 [51 66 96 64 89 12 93 34 49 15]]

Min of filedata : 1

Max of filedata : 99

Sum of filedata : 4675


## Boolean masking and advanced indexing

In [15]:
#check which elements are greater than 50 or not
filedata > 50

array([[False, False, False,  True, False,  True,  True, False,  True,
        False],
       [ True,  True,  True,  True,  True, False,  True,  True, False,
        False],
       [ True,  True, False, False,  True,  True,  True, False, False,
         True],
       [ True, False, False, False, False,  True, False,  True, False,
        False],
       [ True,  True, False,  True, False, False,  True, False, False,
        False],
       [False,  True,  True,  True, False, False, False,  True, False,
        False],
       [ True, False, False,  True,  True, False,  True,  True,  True,
        False],
       [ True, False, False, False,  True,  True,  True,  True, False,
         True],
       [ True,  True,  True,  True,  True, False,  True, False, False,
        False]])

In [16]:
#get all the elements greater than 50
filedata[filedata > 50]

array([85, 99, 55, 61, 83, 79, 58, 57, 80, 97, 54, 53, 63, 92, 88, 62, 60,
       91, 71, 74, 59, 67, 86, 94, 81, 82, 65, 68, 70, 95, 76, 77, 73, 90,
       72, 75, 69, 56, 84, 87, 51, 66, 96, 64, 89, 93])

## Find if any or all the data is equal, greater or whatever 

In [23]:
any = np.any(filedata > 50, axis = 0 )
print(filedata)
print()
print(any)

all_axis0 = np.all(filedata > 50, axis = 0 )
print()
print(all_axis0)

all_axis1 = np.all(filedata > 50, axis = 1 )
print()
print(all_axis1)

[[43 22  7 85 14 99 55 36 61 10]
 [83 79 58 57 80 18 97 54 35 29]
 [53 63 13 27 92 88 62  9 26 60]
 [91 32 17 46 31 71 16 74 11 39]
 [59 67 41 86 19 20 94 47 25 37]
 [ 1 81 82 65 28 40 45 68 30 33]
 [70 42 44 95 76 50 77 73 90 48]
 [72 21  5 38 75 69 56 84 23 87]
 [51 66 96 64 89 12 93 34 49 15]]

[ True  True  True  True  True  True  True  True  True  True]

[False False False False False False False False False False]

[False False False False False False False False False]


In [24]:
# To get if elements are greater than 50 and smaller than 80

((filedata > 50) &(filedata < 80))

array([[False, False, False, False, False, False,  True, False,  True,
        False],
       [False,  True,  True,  True, False, False, False,  True, False,
        False],
       [ True,  True, False, False, False, False,  True, False, False,
         True],
       [False, False, False, False, False,  True, False,  True, False,
        False],
       [ True,  True, False, False, False, False, False, False, False,
        False],
       [False, False, False,  True, False, False, False,  True, False,
        False],
       [ True, False, False, False,  True, False,  True,  True, False,
        False],
       [ True, False, False, False,  True,  True,  True, False, False,
        False],
       [ True,  True, False,  True, False, False, False, False, False,
        False]])

In [25]:
# To get if elements are NOT greater than 50 and smaller than 80

(~((filedata > 50) &(filedata < 80)))

array([[ True,  True,  True,  True,  True,  True, False,  True, False,
         True],
       [ True, False, False, False,  True,  True,  True, False,  True,
         True],
       [False, False,  True,  True,  True,  True, False,  True,  True,
        False],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True],
       [False, False,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True, False,  True,  True,  True, False,  True,
         True],
       [False,  True,  True,  True, False,  True, False, False,  True,
         True],
       [False,  True,  True,  True, False, False, False,  True,  True,
         True],
       [False, False,  True, False,  True,  True,  True,  True,  True,
         True]])

## indexing with a list

In [18]:
# to get the elments 2,4 and 9 from the list

a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

## Quick Little test

- 1 2 3 4 5
- 6 7 8 9 10
- __11__ __12__ 13 14 15
- __16__ __17__ 18 19 20
- 21 22 23 24 25
- 26 27 28 29 30

How will you index the bold elements in the above vector

In [28]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25,],[26,27,28,29,30]])
print(a)

a[2:4,0:2]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


array([[11, 12],
       [16, 17]])

In [29]:
# to get 2,8, 14, 20

a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [36]:
# to get 4, 5, 24, 25, 29 and 30
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25,],[26,27,28,29,30]])
print(a)
a[[0,4,5],3:]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


array([[ 4,  5],
       [24, 25],
       [29, 30]])